services:
  lol_bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: lolbot
    restart: unless-stopped
    env_file:
      - ./bot/.env
    volumes:
      - bot_data:/usr/src/app/data
      - ./bot/src:/usr/src/app/src

volumes:
  bot_data:

