services:
  lol_bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: lolbot
    restart: unless-stopped
    env_file:
      - ./bot/.env
    volumes:
      - ./bot/src:/usr/src/app/src
    depends_on:
      - db

  db:
    image: mongo:7
    container_name: lolbot_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo_data:

